project:
  type: book

execute:
  freeze: auto

book:
  title: "Cloud Architecure"
  author: "Jan Kirenz"
  chapters:
    - intro.qmd
    - key-pairs-create.qmd
    - instance-create.qmd
    - instance-login.qmd
    - docker-setup.qmd
    - instance-storage-increase-docker.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



