# Install Miniconda

Miniconda is a free minimal installer for conda. It is a small, bootstrap version of Anaconda that includes only conda, Python, the packages they depend on, and a small number of other useful packages, including pip, zlib and a few others. 

- The following snippet will create a directory to install miniconda into:

```bash
sudo mkdir /bin/miniconda3/
```

- Download the latest Miniconda installer for Linux:

```bash
sudo wget -P /bin/miniconda3/ https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

```


- Change the directory to /bin/miniconda3/:

```bash
cd /bin/miniconda3/
```

- Make the installer script executable:

```bash
sudo chmod +x Miniconda3-latest-Linux-x86_64.sh

```

- Run the installer script with root permissions:

```bash
sudo ./Miniconda3-latest-Linux-x86_64.sh
```

- The installer will prompt you to accept the license agreement and select the installation directory. Press 'ENTER' to read the license and type 'yes' to accept it. 

- When asked for the installation directory, provide this custom path:

```bash
/home/ubuntu/miniconda3
```

- The installer will install Miniconda and its dependencies. Once the installation is complete, it will ask if you want to initialize Miniconda3 by running conda init. Type 'yes' and press 'ENTER'

- Now we can remove the installer script

```bash
sudo rm -rf /bin/miniconda3/miniconda.sh
```

- Close and reopen your terminal to activate the changes.
