---
title: "Install Python with miniforge"
subtitle: "" 
format: 
  html: 
    embed-resources: true
    theme: 
      - cosmo 
      - custom.scss 
    toc: true 
    number-depth: 3  
    toc-title: Contents 
    toc-location: left 
    number-sections: true 
    html-math-method: mathjax 
    smooth-scroll: true 
---

## Prepare environment

Change directory into your vdc volume:


```bash
cd /mnt/vdc
```

Create a folder called bin

```bash
sudo mkdir bin
```



## Install miniforge

Change into bin

cd bin

https://github.com/conda-forge/miniforge#unix-like-platforms

```bash
sudo curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh"
```

```bash
sudo bash Mambaforge-$(uname)-$(uname -m).sh
```

Press enter and scroll down

Type `yes` and press enter.

If asked, select your partition as location to save mambaforge:

`/mnt/vdc/mambaforge`


Accept and type `yes` when asked.
This will install miniforge to /mnt/vdc/mambaforge

Do you wish the installer to initialize Mambaforge
by running conda init? [yes|no]

Type `yes`


Now add mambaforge to path as shown in the command below:

```bash
export PATH=/mnt/vdc/mambaforge/bin:$PATH
```

Initialize all shells with:


```bash
conda init --all
```

==> For changes to take effect, close and re-open your current shell. <==

---


## Install ipykernel


Run `sudo su`, that will open a shell as the superuser.

```bash
sudo su
```

Install the package ipykernel

```bash
conda install -p /mnt/vdc/mambaforge ipykernel --update-deps --force-reinstall
```

Type `exit` to exit this shell.


-----

OLD

## Install packages

Now add mambaforge to path as shown in the command below:

```bash
export PATH=/mnt/vdc/mambaforge/bin:$PATH
```

Initialize your shell with:

```bash
conda init zsh
```




NOT WORKING

## Change permissions

Read+Write+Execute:

sudo chmod -R a+rwx /var/www


sudo chmod a+rwx /mnt/vdc/mambaforge